version: "3.8"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql83
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sd1991308"
    volumes:
      - /proshoes/docker/_mysqldb/_data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
